# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics

on:
  # Schedule updates (each hour)
  schedule:
    - cron: "0 * * * *"
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push:
    branches:
      - master
      - main

jobs:
  github-metrics:
    environment: production  # 指定 environment 为 production
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}  # 使用 secrets.METRICS_TOKEN

          # Options
          user: mengnankkkk
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Shanghai
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_load: 300
          plugin_activity_visibility: all
          plugin_introduction: yes
          plugin_introduction_title: yes
