name: generate-snake

on:
  # 每 12 小时自动运行一次
  schedule:
    - cron: "0 */12 * * *"
  
  # 允许手动触发执行
  workflow_dispatch:
  
  # 每当push到master分支时自动执行
  push:
    branches:
      - master

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # 生成 GitHub 贡献图表的蛇形动画并输出为 SVG 文件
      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v2
        with:
          github_user_name: ${{ github.repository_owner }}  # 确保此变量正确传递
          outputs: dist/github-contribution-grid-snake.svg  # 简化输出路径，避免问题

      # 将生成的文件推送到指定的 output 分支
      - name: Push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

