name: generate-snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # 调试步骤：输出 github_user_name
      - name: Debug github_user_name
        run: echo "GitHub User Name: ${{ github.repository_owner }}"

      # 生成 GitHub 贡献图表的蛇形动画并输出为 SVG 文件
      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v2
        with:
          github_user_name: "mengnankkkk"  # 使用提供的 GitHub 用户名
          outputs: dist/github-contribution-grid-snake.svg

      # 将生成的文件推送到指定的 output 分支
      - name: Push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
